name: PEP8

on:
  workflow_dispatch:
  push:
#    branches:
#      - master
#  pull_request:

jobs:
  build:

    #runs-on: ubuntu-latest
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [3.7, 3.9]

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: fink-broker
      run: |
        flake8 fink_broker/*.py --count --show-source --statistics --ignore=E302,E501,E731

    - name: bin
      run: |
        flake8 bin/*.py --count --show-source --statistics --ignore=E302,E501,E731
